[build]
  publish = "frontend"
  functions = "netlify/functions"
  command = "bash build.sh"

[build.environment]
  PYTHON_VERSION = "3.8"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200