[build]
  publish = "frontend"  # Directory with your static files
  functions = "netlify/functions"  # Directory with your Netlify functions
  command = "pip install -r requirements.txt"

[dev]
  publish = "frontend"
  functions = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200


[build.environment]
  PYTHON_VERSION = "3.11.5"